# Generated by Django 5.1 on 2024-09-03 02:13

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('description', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('chairman', models.CharField(max_length=100)),
                ('founded_year', models.IntegerField()),
                ('valuation', models.DecimalField(decimal_places=2, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employees_count', models.IntegerField()),
                ('business_registration_certificate', models.FileField(upload_to='business_docs/registration_certificates/')),
                ('tax_identification_number', models.FileField(upload_to='business_docs/tax_ids/')),
                ('proof_of_address', models.FileField(upload_to='business_docs/proof_of_address/')),
                ('financial_statements', models.FileField(blank=True, null=True, upload_to='business_docs/financial_statements/')),
                ('ownership_documents', models.FileField(upload_to='business_docs/ownership_documents/')),
                ('director_identification', models.FileField(upload_to='business_docs/director_identification/')),
                ('licenses_and_permits', models.FileField(blank=True, null=True, upload_to='business_docs/licenses_and_permits/')),
                ('bank_account_details', models.FileField(upload_to='business_docs/bank_account_details/')),
            ],
            options={
                'verbose_name': 'Business',
                'verbose_name_plural': 'Businesses',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(blank=True, max_length=10, null=True)),
                ('financial_statements', models.FileField(upload_to='investor_docs/financial_statements')),
            ],
            options={
                'verbose_name': 'Investor',
                'verbose_name_plural': 'Investors',
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FundRaising',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('deadline_date', models.DateField()),
                ('minimum_investment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shares_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2d.business')),
            ],
        ),
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('shares_percentage', models.DecimalField(decimal_places=2, max_digits=4)),
                ('investment_status', models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('wait', 'Wait')], default='wait', max_length=10)),
                ('fundraise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2d.fundraising')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='b2d.investor')),
            ],
            options={
                'verbose_name': 'Investment',
                'verbose_name_plural': 'Investments',
            },
        ),
    ]
