# Generated by Django 5.1 on 2024-09-07 15:42

import b2d.models.business
import b2d.models.investor
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='b2d.category'),
        ),
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='business',
            name='bank_account_details',
            field=models.FileField(upload_to=b2d.models.business.bank_account_details_path),
        ),
        migrations.AlterField(
            model_name='business',
            name='business_registration_certificate',
            field=models.FileField(upload_to=b2d.models.business.business_registration_certificate_path),
        ),
        migrations.AlterField(
            model_name='business',
            name='director_identification',
            field=models.FileField(upload_to=b2d.models.business.director_identification_path),
        ),
        migrations.AlterField(
            model_name='business',
            name='financial_statements',
            field=models.FileField(blank=True, null=True, upload_to=b2d.models.business.financial_statements_path),
        ),
        migrations.AlterField(
            model_name='business',
            name='licenses_and_permits',
            field=models.FileField(blank=True, null=True, upload_to=b2d.models.business.licenses_and_permits_path),
        ),
        migrations.AlterField(
            model_name='business',
            name='ownership_documents',
            field=models.FileField(upload_to=b2d.models.business.ownership_documents_path),
        ),
        migrations.AlterField(
            model_name='business',
            name='proof_of_address',
            field=models.FileField(upload_to=b2d.models.business.proof_of_address_path),
        ),
        migrations.AlterField(
            model_name='business',
            name='tax_identification_number',
            field=models.FileField(upload_to=b2d.models.business.tax_identification_number_path),
        ),
        migrations.AlterField(
            model_name='investor',
            name='financial_statements',
            field=models.FileField(upload_to=b2d.models.investor.investor_document_path),
        ),
    ]
