# Generated by Django 5.1 on 2024-11-12 08:40

import b2d.models.investment
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2d', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='transaction_slip',
            field=models.FileField(max_length=1024, null=True, upload_to=b2d.models.investment.transaction_slip_upload_path),
        ),
    ]
