# Generated by Django 4.2.4 on 2024-11-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2d", "0002_alter_investment_transaction_slip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="category",
        ),
        migrations.AddField(
            model_name="business",
            name="category",
            field=models.ManyToManyField(blank=True, null=True, to="b2d.category"),
        ),
    ]
