# Generated by Django 5.1 on 2024-09-14 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2d', '0002_business_category_business_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fundraising',
            options={'verbose_name': 'Fundraising', 'verbose_name_plural': 'Fundraisings'},
        ),
        migrations.AddField(
            model_name='fundraising',
            name='fundraising_status',
            field=models.CharField(choices=[('approve', 'Approve'), ('reject', 'Reject'), ('wait', 'Wait')], default='wait', max_length=10),
        ),
    ]
