# Generated by Django 5.1 on 2024-11-14 14:10

import b2d.models.investor
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2d', '0003_remove_business_category_business_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'verbose_name': 'Business Registration', 'verbose_name_plural': 'Business Registrations'},
        ),
        migrations.AlterModelOptions(
            name='fundraising',
            options={'verbose_name': 'Fundraising Campaign', 'verbose_name_plural': 'Fundraising Campaigns'},
        ),
        migrations.AlterModelOptions(
            name='investment',
            options={'verbose_name': 'Investment Request', 'verbose_name_plural': 'Investment Requests'},
        ),
        migrations.AlterModelOptions(
            name='investor',
            options={'verbose_name': 'Investor Registration', 'verbose_name_plural': 'Investor Registrations'},
        ),
        migrations.RemoveField(
            model_name='fundraising',
            name='shares_percentage',
        ),
        migrations.AddField(
            model_name='fundraising',
            name='share_type',
            field=models.CharField(choices=[('common', 'Common Stock'), ('preferred', 'Preferred Stock')], default='common', max_length=10),
        ),
        migrations.AddField(
            model_name='fundraising',
            name='shares',
            field=models.IntegerField(default=100000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.ManyToManyField(blank=True, to='b2d.category'),
        ),
        migrations.AlterField(
            model_name='investor',
            name='financial_statements',
            field=models.FileField(blank=True, null=True, upload_to=b2d.models.investor.investor_document_path),
        ),
    ]
