# Generated by Django 5.1 on 2024-11-14 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('b2d', '0004_alter_business_options_alter_fundraising_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='shares_percentage',
        ),
    ]
