# Generated by Django 5.1 on 2024-09-20 01:39

import b2d.models.investment
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b2d', '0004_alter_fundraising_publish_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='investment_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='investment',
            name='transaction_slip',
            field=models.FileField(null=True, upload_to=b2d.models.investment.transaction_slip_upload_path),
        ),
    ]
