# Generated by Django 4.2.4 on 2024-10-06 14:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2d", "0005_investment_investment_datetime_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
