# Generated by Django 5.1.1 on 2024-11-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("b2d", "0008_topdeal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fundraising",
            name="minimum_investment",
        ),
        migrations.AddField(
            model_name="fundraising",
            name="minimum_shares",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
