# Generated by Django 5.1.1 on 2024-12-08 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("b2d", "0009_remove_fundraising_minimum_investment_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={
                "permissions": [
                    (
                        "manage_fundraising_dashboard",
                        "Can manage the fundraising dashboard",
                    ),
                    ("manage_business_profile", "Can manage business profile"),
                ],
                "verbose_name": "Business Registration",
                "verbose_name_plural": "Business Registrations",
            },
        ),
        migrations.AlterModelOptions(
            name="investor",
            options={
                "permissions": [
                    ("view_portfolio", "Can manage the fundraising dashboard"),
                    ("make_investment", "Can view fundraising details"),
                    ("update_investor_profile", "Can view fundraising details"),
                ],
                "verbose_name": "Investor Registration",
                "verbose_name_plural": "Investor Registrations",
            },
        ),
    ]
