# Generated by Django 5.1.1 on 2024-12-09 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("b2d", "0011_alter_investor_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={
                "permissions": [
                    ("view_investments", "Can view investments"),
                    ("manage_business_profile", "Can manage business profile"),
                ],
                "verbose_name": "Business Registration",
                "verbose_name_plural": "Business Registrations",
            },
        ),
    ]
